# security:
#   - api_key: []

# securityDefinitions:
#   #this section configures basic authentification with an API key
#   api_key:
#     type: "apiKey"
#     name: "key"
#     in: "query"
swagger: "2.0"
info: 
  title: "projet api"
  description: "Project for ACS formation: An api for communicate with a Monster Hunter monsters and weapons database"
  termsOfService: None 
  version: "1.0.0"
host: "localhost"
schemes: 
  - "http"

basePath: "/FOLDERS/FORM_PROJETS/form_projet_api/projet_api/api"
paths:
  "/monsters":
    get:
      tags:
      - monster
      summary:  Retourne la liste des monstres
      #description: 
      operationId: getMonsters
      consumes: []
      produces:
      - application/json
      responses:
        '200':
          description: liste des monstres
          schema: 
            "$ref": "#/definitions/monster"
  "/monsters/{id}":
    get:
      tags:
      - monster
      summary: Retourne un monstre specifique a partir de son id
      description: ""
      operationId: getMonstersDetails
      consumes: []
      produces: 
      - application/json
      parameters:
      - name: id
        in: path
        description: id du monstre à retourner
        required: true
        type: integer
      responses:
        '200':
          description: monstre selectionné
          schema:
            "$ref": "#/definitions/monster"
  "/monsters/{field}/{value}":
    get:
      tags:
      - monster
      summary: Retourne la liste des monstres dont la propriété {field} est égale à {value}
      description: ""
      operationId: getMonstersByField
      consumes: []
      produces: 
      - application/json
      parameters:
      - name: field
        in: path
        description: nom de colonne de la base ou l'on va chercher la valeur renseignée
        required: true
        type: string
      - name: value
        in: path
        description: valeur à rechercher dans la colonne renseignée
        required: true
        type: string
      responses:
        '200':
          description: monstres dont la propriété {field} correspond à {value}
          schema:
            "$ref": "#/definitions/monster"
  "/weapons/weapon_type/{weapon_type}":
    get:
      tags:
      - weapon
      summary: Retourne la liste des armes de cette categorie
      #description: 
      operationId: getWeaponsByCategory
      consumes: []
      produces:
      - application/json
      parameters:
      - name: weapon_type
        in: path
        description: type d'arme a retourner
        required: true
        type: string
      responses:
        '200':
          description: liste d'arme de la categorie demandée
          schema:
            "$ref": "#/definitions/weapon" 
  "/weapons/weapon_type/{weapon_type}/order_by/{field}":
    get:
      tags:
      - weapon
      summary: Retourne la liste des armes d'une certaine catégorie, ordonnée en fonction du {field} renseigné
      # description: 
      operationId: getWeaponsByCategory
      parameters:
      - name: weapon_type
        in: path
        description: type d'arme a retourner
        required: true
        type: string
      - name: field
        in: path
        description: champ par lequel ordonner la liste
        required: true
        type: string
      responses:
        '200':
          description: Renvoi la liste des armes de la categorie demandée, ordonnée en fonction du {field}
          schema:
            "$ref": "#/definitions/weapon"
  "/weapons/weapon_type/{weapon_type}/filter/{field}/{value}"
    get:
      tags:
      - weapon
      summary: Filtre la liste des armes
      description: Retourne une liste d'arme de la catégorie renseignée dont le champ {field} contient la {value} renseignée
      operationId: getCategoryWeaponsByField
      parameters:
        - name: weapon_type
          in: path
          description: type d'arme a retourner
          required: true
          type: string
        - name: field
          in: path
          description: champ dans lequel on recherchera la {value}
          required: true
          type: string
        - name: value
          in: path
          description: valeur à trouver dans le champ {field}
          required: true
          type: string
        responses:
          '200':
            description: Renvoi la liste d'arme correspondante
            schema:
              "$ref": "#/descriptions/weapon"
definitions:
  monster:
    type: object
    properties:
      id: 
        type: integer
      name_en:
        type: string
      ecology_en:
        type: string
      pitfall_trap:
        type: boolean
      shock_trap:
        type: boolean
      vine_trap:
        type: boolean
      size:
        type: string
  weapon:
    type: object
    properties:
      id:
        type: integer
      weapon_type:
        type: string
      rarity:
        type: integer
      element1:
        type: string
      element1_attack:
        type: string
      previous_en:
        type: string
      affinity: 
        type: string
      attack:
        type: string